apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: wordpress-prod
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-secret
                  key: mariadb-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: wp-config
                  key: mariadb-database
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: wp-config
                  key: mariadb-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-secret
                  key: mariadb-user-password
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ebs-sc
        resources:
          requests:
            storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-storage-mysql-0
  namespace: wordpress-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ebs-sc


